# Site settings
title: David Rusu
email: davidrusu.me@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hey there, here's some stuff I've been working
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://davidrusu.github.io/" # the base hostname & protocol for your site
twitter_username: davidrusu
github_username:  davidrusu

# Build settings
markdown: kramdown
